### ISSUE TITLE
Requests time out on Windows 7

### ISSUE THREAD

**Issue by rk** [mongrel/mongrel#1]
When I use Mongrel to run a Sinatra application, all requests time out after the first source is delivered. Sinatra/Rack returns full source, but the connection is never closed.

Webrick doesn't have this problem, but I'd sure love to use Mongrel again.

**Comment by ghazel** [comment]
I'm using Mongrel and Sinatra on Windows 7, and it seems to work fine. How are you testing this?

**Comment by rk** [comment]
Sorry, I own a Mac now and can't go back to my old machine. I didn't even know that this was still open.
