### ISSUE TITLE
Who wants to own mongrel/mongrel.git

### ISSUE THREAD

**Issue by timcharper** [mongrel/mongrel#2]
I set up mongrel on github, and it looks like since then a lot of people have forked it.  I no longer do any work with mongrel.  Is there anyone particularly motivated in taking over has unintentionally become the official mongrel github account? (I have no authority to call it as such, but it just appears many have gotten that impression).

Who is actively maintaining mongrel?

**Comment by peteonrails** [comment]
I'd be happy to take it over. What was your time commitment like at the height of things?

**Comment by kudelabs** [comment]
thanks for stepping up. there is one patch that I need, it would be great if someone started accepting patches again.

**Comment by coffeeaddict** [comment]
Honesty rocks!

I will not be able to take over the (un)official mongrel github account, good luck finding someone (may I say happy huntin'?)

**Comment by timcharper** [comment]
my time commitment was very little, actually. I just put it up here so I could create my own fork of mongrel and apply / polish the forked mongrel patch... (which unicorn now better implements).

Pete, if you're good with it, I will email you the password to the account and you can take it from there.
